[package]
name = "ggvtogpx"
version = "0.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = "4.5.51"
encoding_rs = "0.8.35"
nom = "8.0.0"
quick-xml = "0.38.4"
roxmltree = "0.21.1"
zip = "5.1.1"
